### ISSUE TITLE
Users without a verified email can sign in

### ISSUE THREAD

**Issue by rbarman** [PinkShirtBoys/ThinkTank#1]
Does Parse allow users to log in without a verified email?

Currently users with the emailVerified field set to 'false' or 'undefined' can log in. 

We want users to have a verified email to prevent some level of spam.

**Comment by pranavpunjabi** [comment]
Issue Resolved. 
27e270618f7e41ec15b4a879971430e2efbd7a21

**Comment by rbarman** [comment]
What if the emailVerified field is undefined? There are a couple Users with this condition. Are we setting emailVerified to be false when creating a User?

**Comment by pranavpunjabi** [comment]
For this we will have to switch to previously discussed model:

email (UI) = username(Parse) = email(Parse)
We will have to ask the user to enter email address. Hence emailVerified will never be undefined.

This will automatically cover the ground for redundant usernames as email Id is always unique

**Comment by rbarman** [comment]
Ok so the SignUp view and controller will need to be changed to reflect this.

**Comment by pranavpunjabi** [comment]
I have changed it locally. Will push it soon! You don't make any changes on your end.

**Comment by pranavpunjabi** [comment]
Working Code Pushed

**Comment by rbarman** [comment]
I don't know if this is an issue with parse, but I got an email confirmation link (https://www.parse.com/apps/thinktank—3/verify_email?token=DH4gXlHTA3PbBulDgWRxk4BIh&username=gokovidu%40freeletter.me) and that leads to a 404 page. My email is still unverified. 

Is this something out of our control?

**Comment by pranavpunjabi** [comment]
Try using a real email. I tried with two accounts and it works fine.

[Update]: When I use a fake email, I don't even receive a link. The mail I receive says to click on a link, but there is no link. Parse is not dealing well with fake IDs.

**Comment by rbarman** [comment]
Ok it works for my gmail. In the future we should find out which email domains Parse will accept and alert the user if their email will not be accepted because Parse takes in the email as valid email.

**Comment by pranavpunjabi** [comment]
Check FB then delete this comment
